apiVersion: v1
kind: ServiceAccount
metadata:
  name: jumpserver-koko
---
apiVersion: v1
kind: Secret
metadata:
  name: jumpserver-koko-token
  annotations:
    kubernetes.io/service-account.name: jumpserver-koko
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jumpserver-koko-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # or specify a more restrictive role as needed
subjects:
- kind: ServiceAccount  # or use 'ServiceAccount' if it's a service account
  name: jumpserver-koko
  namespace: {{ .Release.Namespace }}


