---
# Source: jumpserver/templates/web/configmap-web.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: "jumpserver-jms-web"
  labels:
    app.kubernetes.io/name: jumpserver
    helm.sh/chart: jumpserver-v4.3.1
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/version: "v4.3.1"
    app.kubernetes.io/managed-by: Helm
    app.jumpserver.org/name: jms-web
data:
  default.conf: |
    
    
    
    
    
    server {
        listen 80;
        server_name  _;
        server_tokens off;
  
        client_max_body_size 4096m;
  
        location = /robots.txt {
            default_type text/html;
            add_header Content-Type "text/plain; charset=UTF-8";
            return 200 "User-agent: *\nDisallow: /\n";
        }
        location /web/health/ {
            access_log off;
            add_header Content-Type 'application/json';
            return 200 '{"status": "ok"}';
        }
        location /ui/ {
            try_files $uri / /index.html;
            alias /opt/lina/;
        }
        location /luna/ {
            try_files $uri / /index.html;
            alias /opt/luna/;
        }
        location /download/ {
            alias /opt/download/;
            try_files $uri @redirect_oss;
        }
        location @redirect_oss {
            rewrite ^/download/(.*)$ https://static.jumpserver.org/download/$1 permanent;
        }
        location /static/ {
            root /opt/jumpserver/data/;
        }
        location /private-media/ {
            internal;
            alias /opt/jumpserver/data/media/;
        }
        location /koko/ {
            proxy_pass http://jumpserver-jms-koko:5000;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ignore_client_abort on;
        }
        location /lion/ {
            proxy_pass http://jumpserver-jms-lion:8081;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ignore_client_abort on;
        }
        location /chen/ {
            proxy_pass http://jumpserver-jms-chen:8082;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ignore_client_abort on;
        }
        
        location /ws/ {
            proxy_pass http://jumpserver-jms-core:8080;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location ~ ^/(core|api|media)/ {
            proxy_pass http://jumpserver-jms-core:8080;
            proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
            rewrite ^/(.*)$ /ui/$1 last;
        }
    }
