---
# Source: jumpserver/templates/web/pvc-web-logs.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jumpserver-jms-web-logs"
  labels:
    app.kubernetes.io/name: jumpserver
    helm.sh/chart: jumpserver-v4.3.1
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/version: "v4.3.1"
    app.kubernetes.io/managed-by: Helm
    app.jumpserver.org/name: jms-web
  annotations:
    helm.sh/resource-policy: keep
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: local-path
