---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: "infra-jumpserver"
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.0.0
    helm.sh/chart: postgresql-16.1.2
type: Opaque
data:
  postgres-password: "cGFzc3dvcmQ="
  password: "anVtcHNlcnZlcg=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
